name: one_line_text_style
description: Generates TextStyle extentions
version: 0.3.0
repository: https://github.com/vlytvyne/one_line_text_style
issue_tracker: https://github.com/vlytvyne/one_line_text_style/issues

topics:
  - ui
  - codegen
  - widgets

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  code_builder: ^4.7.0
  dart_style: ^2.3.3
  yaml: ^3.1.2
  args: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter