name: one_line_text_style
description: This package simplifies the process of creating and applying text styles by introducing a set of convenient extensions, making your more readable.
version: 0.4.0
repository: https://github.com/vlytvyne/one_line_text_style
issue_tracker: https://github.com/vlytvyne/one_line_text_style/issues

topics:
  - ui
  - codegen
  - widgets

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  yaml: ^3.0.0
  args: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter